/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alquilervehiculos.vista;

import alquilervehiculos.controlador.GestionUsuario;
import alquilervehiculos.modelo.Usuario;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junor
 */
public class MdiVehiculos extends javax.swing.JFrame {
private GestionUsuario gestionUsuario;
private Usuario usuarioAutenticado;
    /**
     * Creates new form MdiVehiculos
     */
    public MdiVehiculos() {
        initComponents();
       JifUsuarios.hide();
       JifMoto.hide();
    }

    
     private void iniciarMenus(boolean estado) {
        MnuVehiculos.setVisible(estado);
        MnuCoche.setVisible(estado);
        MnuFurgoneta.setVisible(estado);
        MnuMoto.setVisible(estado);
        MnuUsuarios.setVisible(estado);
        MnuCrearusuario.setVisible(estado);
    }

    private void gestionarPermisosMenu() {

        switch (usuarioAutenticado.getTipoUsuario().getCodigo()) {
            ///administrador
            case "1":
                iniciarMenus(true);
                break;
            ///alquiler
            case "2":
                iniciarMenus(false);
                MnuUsuarios.setVisible(true);
                MnuVehiculos.setVisible(true);
                MnuMoto.setVisible(true);
                MnuCoche.setVisible(true);
                MnuFurgoneta.setVisible(true);
                break;
            ///Secretaria
            case "3":
                iniciarMenus(false);
                MnuCoche.setVisible(true);
                MnuMoto.setVisible(true);
                MnuFurgoneta.setVisible(true);
                MnuVehiculos.setVisible(true);
                break;

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        JflmLogin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtContraseña = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtCorreo = new javax.swing.JTextPane();
        BtnIngresar = new javax.swing.JButton();
        JifUsuarios = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblUsuarios = new javax.swing.JTable();
        JifMoto = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblMoto = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        MmuLogin = new javax.swing.JMenu();
        MnuVehiculos = new javax.swing.JMenu();
        MnuCoche = new javax.swing.JMenuItem();
        MnuFurgoneta = new javax.swing.JMenuItem();
        MnuMoto = new javax.swing.JMenuItem();
        MnuUsuarios = new javax.swing.JMenuItem();
        MnuCrearusuario = new javax.swing.JMenuItem();
        MnuCerrarSesion = new javax.swing.JMenuItem();
        MnuSalirr = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JflmLogin.setIconifiable(true);
        JflmLogin.setResizable(true);
        JflmLogin.setTitle("Login");
        JflmLogin.setVisible(true);

        jLabel1.setText("*Correo:");

        jLabel2.setText("*Contraseña:");

        jScrollPane1.setViewportView(TxtCorreo);

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JflmLoginLayout = new javax.swing.GroupLayout(JflmLogin.getContentPane());
        JflmLogin.getContentPane().setLayout(JflmLoginLayout);
        JflmLoginLayout.setHorizontalGroup(
            JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JflmLoginLayout.createSequentialGroup()
                .addGroup(JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JflmLoginLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(TxtContraseña)))
                    .addGroup(JflmLoginLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        JflmLoginLayout.setVerticalGroup(
            JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JflmLoginLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        desktopPane.add(JflmLogin);
        JflmLogin.setBounds(30, 30, 420, 280);

        JifUsuarios.setClosable(true);
        JifUsuarios.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifUsuarios.setIconifiable(true);
        JifUsuarios.setMaximizable(true);
        JifUsuarios.setResizable(true);
        JifUsuarios.setTitle("Listado De Usuarios");
        JifUsuarios.setVisible(false);

        TblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cedula", "Correo", "Password", "Tipo usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TblUsuarios);

        javax.swing.GroupLayout JifUsuariosLayout = new javax.swing.GroupLayout(JifUsuarios.getContentPane());
        JifUsuarios.getContentPane().setLayout(JifUsuariosLayout);
        JifUsuariosLayout.setHorizontalGroup(
            JifUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JifUsuariosLayout.setVerticalGroup(
            JifUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifUsuariosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        desktopPane.add(JifUsuarios);
        JifUsuarios.setBounds(170, 30, 519, 371);

        JifMoto.setClosable(true);
        JifMoto.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifMoto.setIconifiable(true);
        JifMoto.setMaximizable(true);
        JifMoto.setResizable(true);
        JifMoto.setTitle("Listado de Motos");
        JifMoto.setVisible(false);

        TblMoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Km", "Estado", "Valor alquiler", "Casco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TblMoto);

        javax.swing.GroupLayout JifMotoLayout = new javax.swing.GroupLayout(JifMoto.getContentPane());
        JifMoto.getContentPane().setLayout(JifMotoLayout);
        JifMotoLayout.setHorizontalGroup(
            JifMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifMotoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JifMotoLayout.setVerticalGroup(
            JifMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifMotoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        desktopPane.add(JifMoto);
        JifMoto.setBounds(210, 10, 510, 352);

        MmuLogin.setMnemonic('f');
        MmuLogin.setText("Menu");
        MmuLogin.setEnabled(false);

        MnuVehiculos.setText("Vehiculos");

        MnuCoche.setText("Coche");
        MnuCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCocheActionPerformed(evt);
            }
        });
        MnuVehiculos.add(MnuCoche);

        MnuFurgoneta.setText("Furgoneta");
        MnuFurgoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuFurgonetaActionPerformed(evt);
            }
        });
        MnuVehiculos.add(MnuFurgoneta);

        MnuMoto.setText("Moto");
        MnuMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuMotoActionPerformed(evt);
            }
        });
        MnuVehiculos.add(MnuMoto);

        MmuLogin.add(MnuVehiculos);

        MnuUsuarios.setMnemonic('s');
        MnuUsuarios.setText("Usuarios");
        MnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuUsuariosActionPerformed(evt);
            }
        });
        MmuLogin.add(MnuUsuarios);

        MnuCrearusuario.setText("Crear usuario");
        MmuLogin.add(MnuCrearusuario);

        MnuCerrarSesion.setMnemonic('x');
        MnuCerrarSesion.setText("Cerrar sesion");
        MnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCerrarSesionActionPerformed(evt);
            }
        });
        MmuLogin.add(MnuCerrarSesion);

        MnuSalirr.setText("Salir");
        MnuSalirr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSalirrActionPerformed(evt);
            }
        });
        MmuLogin.add(MnuSalirr);

        menuBar.add(MmuLogin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCerrarSesionActionPerformed
         MmuLogin.setEnabled(false);
        TxtCorreo.setText("");
        TxtContraseña.setText("");
        usuarioAutenticado = null;
        iniciarMenus(false);
        JflmLogin.show();


    }//GEN-LAST:event_MnuCerrarSesionActionPerformed

     private void pintarUsuarios() {
        DefaultTableModel model = (DefaultTableModel) TblUsuarios.getModel();
        model.getDataVector().removeAllElements();
        for (Usuario usuario: gestionUsuario.getUsuarios()) {
            model.addRow(usuario.obtenerArregloObjeto());
        }
        TblUsuarios.setModel(model);

    }

    
    
    private void MnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuUsuariosActionPerformed
        // TODO add your handling code here:
         gestionUsuario.llenarUsuarios();
        pintarUsuarios();
        JifUsuarios.repaint();
        JifUsuarios.show();
        if (JifUsuarios.isIcon()) {
            try {
                JifUsuarios.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_MnuUsuariosActionPerformed

    private void MnuCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuCocheActionPerformed

    private void MnuFurgonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuFurgonetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuFurgonetaActionPerformed

    private void MnuMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuMotoActionPerformed
        // TODO add your handling code here:
        
        JifMoto.show();
        
         if (JifMoto.isIcon()) {
            try {
                JifMoto.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_MnuMotoActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        // TODO add your handling code here:
          if(TxtCorreo.getText()==null || TxtCorreo.getText().compareTo("")==0){
            JOptionPane.showMessageDialog(this,  
                    "Debe diligenciar el correo","Datos Faltantes",2);
        }else if(TxtContraseña.getPassword().length == 0){
            JOptionPane.showMessageDialog(this,  
                    "Debe diligenciar la contraseña","Datos Faltantes",2);
        } else{
              gestionUsuario = new GestionUsuario();

            //Significa que diligencio correo y contraseña
            Pattern pattern = Pattern.compile("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");
            Matcher matcher = pattern.matcher(TxtCorreo.getText());

            if (matcher.find() == true) {
                usuarioAutenticado = gestionUsuario.
                        encontrarUsuario(TxtCorreo.getText(), TxtContraseña.getText());
                if (usuarioAutenticado == null) {
                    JOptionPane.showMessageDialog(this,
                            "El usuario Ingresado no existe", "Datos Erróneos", 0);
                } else {
                    gestionUsuario = new GestionUsuario();

                    JOptionPane.showMessageDialog(this,
                            "Bienvenido " + usuarioAutenticado, "Bienvenido", 1);
                    MmuLogin.setEnabled(true);
                    gestionarPermisosMenu();
                    JflmLogin.hide();
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "El correo no tiene un formato válido", "Datos Erróneos", 0);

            }

        }
    }             
           /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiVehiculos().setVisible(true);
            }
        });
    }

    
    

    
     {
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void MnuSalirrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSalirrActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_MnuSalirrActionPerformed
                            
////
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JInternalFrame JflmLogin;
    private javax.swing.JInternalFrame JifMoto;
    private javax.swing.JInternalFrame JifUsuarios;
    private javax.swing.JMenu MmuLogin;
    private javax.swing.JMenuItem MnuCerrarSesion;
    private javax.swing.JMenuItem MnuCoche;
    private javax.swing.JMenuItem MnuCrearusuario;
    private javax.swing.JMenuItem MnuFurgoneta;
    private javax.swing.JMenuItem MnuMoto;
    private javax.swing.JMenuItem MnuSalirr;
    private javax.swing.JMenuItem MnuUsuarios;
    private javax.swing.JMenu MnuVehiculos;
    private javax.swing.JTable TblMoto;
    private javax.swing.JTable TblUsuarios;
    private javax.swing.JPasswordField TxtContraseña;
    private javax.swing.JTextPane TxtCorreo;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

     } 

