/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alquilervehiculos.vista;

import alquilervehiculos.controlador.GestionUsuario;
import alquilervehiculos.controlador.GestionVehiculo;
import alquilervehiculos.excepciones.ClienteExcepcion;
import alquilervehiculos.excepciones.VehiculoExcepcion;
import alquilervehiculos.modelo.AbstractVehiculo;
import alquilervehiculos.modelo.AlquilaVehiculo;
import alquilervehiculos.modelo.Cliente;
import alquilervehiculos.modelo.Coche;
import alquilervehiculos.modelo.Furgoneta;
import alquilervehiculos.modelo.Moto;
import alquilervehiculos.modelo.TipoUsuario;
import alquilervehiculos.modelo.Usuario;
import alquilervehiculos.utilidades.LeerArchivoPlano;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junor
 */
public class MdiVehiculos extends javax.swing.JFrame {

    private GestionUsuario gestionUsuario;
    private Usuario usuarioAutenticado;
    private GestionVehiculo gestionVehiculo;
    private int tipoUsuario;
    private GestionUsuario gestionUsuario1;
    private LeerArchivoPlano leer;

    /**
     * Creates new form MdiVehiculos
     */
    public MdiVehiculos() {
        initComponents();
        gestionVehiculo = new GestionVehiculo();
        gestionUsuario1 = new GestionUsuario();
//        JifUsuarios.hide();
//        JifMoto.hide();
    }

    private void iniciarMenus(boolean estado) {
        MnuVehiculos.setVisible(estado);
        MnuCoche.setVisible(estado);
        MnuFurgoneta.setVisible(estado);
        MnuMoto.setVisible(estado);
        MnuUsuarios.setVisible(estado);
        MnuCrearusuario.setVisible(estado);
    }

    private void gestionarPermisosMenu() {

        switch (usuarioAutenticado.getTipoUsuario().getCodigo()) {
            ///administrador
            case "1":
                iniciarMenus(true);
                MnuVehiculos.setVisible(true);
                MnuCoche.setVisible(true);
                MnuFurgoneta.setVisible(true);
                MnuMoto.setVisible(true);
                MnuCrearusuario.setVisible(true);
                MnuInformeVehiculos.setVisible(true);
                MnuInformeAlquilados.setVisible(true);
                MnuInformes.setVisible(true);
                MnuUsuarios.setVisible(true);

                break;
            ///alquiler
            case "2":
                iniciarMenus(false);
                MnuUsuarios.setVisible(true);
                MnuVehiculos.setVisible(true);
                MnuMoto.setVisible(true);
                MnuCoche.setVisible(true);
                MnuFurgoneta.setVisible(true);
                break;
            ///Secretaria
            case "3":
                iniciarMenus(false);
                MnuCoche.setVisible(true);
                MnuMoto.setVisible(true);
                MnuFurgoneta.setVisible(true);
                MnuVehiculos.setVisible(true);
                break;

        }
    }

    public void validarCreacionVehi() {

        if (JcbMoto.isSelected()) {
            JcbCasco.setEnabled(true);
        } else {
            JcbCasco.setEnabled(false);
        }
        if (JcbCoche.isSelected()) {
            JcbExtras.setEnabled(true);
        } else {
            JcbExtras.setEnabled(false);
        }
        if (JcbFurgoneta.isSelected()) {
            JspCapacidad.setEnabled(true);
        } else {
            JspCapacidad.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        desktopPane = new javax.swing.JDesktopPane();
        JflmLogin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtContraseña = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtCorreo = new javax.swing.JTextPane();
        BtnIngresar = new javax.swing.JButton();
        JifUsuarios = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblUsuarios = new javax.swing.JTable();
        JifMoto = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblMoto = new javax.swing.JTable();
        BtnDevolverMoto = new javax.swing.JButton();
        BtnAlquilarMoto = new javax.swing.JButton();
        JifCoche = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        TblCoche = new javax.swing.JTable();
        BtnDevolverCoche = new javax.swing.JButton();
        BtnAlquilarCoche = new javax.swing.JButton();
        JifFurgoneta = new javax.swing.JInternalFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        TblFurgoneta = new javax.swing.JTable();
        BtnAlquilarFurgoneta = new javax.swing.JButton();
        BtnDevolverFurgoneta = new javax.swing.JButton();
        JifAlquilarVehiculos = new javax.swing.JInternalFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        TblVehiculos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        TxtMatriculaAlquilar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtNombreClienteAlquiler = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateEntregaAlquiler = new com.toedter.calendar.JDateChooser();
        jDateDevolucionAlquiler = new com.toedter.calendar.JDateChooser();
        BtnAlquilar = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        TblCliente = new javax.swing.JTable();
        JifCrearUsuario = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        TxtNombreCrearUsuario = new javax.swing.JTextField();
        TxtIdentifiacionCrearUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtCorreoCrearUsu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtContraseñaCrearUsu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnCrearUsu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CbxTipoUsuario = new javax.swing.JComboBox<>();
        JifInformeAlquilados = new javax.swing.JInternalFrame();
        jScrollPane7 = new javax.swing.JScrollPane();
        TblVehiculosAlquilados = new javax.swing.JTable();
        JifCrearVehiculo = new javax.swing.JInternalFrame();
        jLabel12 = new javax.swing.JLabel();
        JcbCoche = new javax.swing.JCheckBox();
        JcbFurgoneta = new javax.swing.JCheckBox();
        JcbMoto = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        TxtMatriculaCrearVehiculo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtKmCrearVehi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TxtValorCrearVehi = new javax.swing.JTextField();
        JcbDisponible = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        JcbCasco = new javax.swing.JCheckBox();
        JcbExtras = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        JspCapacidad = new javax.swing.JSpinner();
        BtnCrearVehiculo = new javax.swing.JButton();
        JifInformeVehiculos = new javax.swing.JInternalFrame();
        jScrollPane10 = new javax.swing.JScrollPane();
        TblInformeVehiculos = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        MmuLogin = new javax.swing.JMenu();
        MnuVehiculos = new javax.swing.JMenu();
        MnuCoche = new javax.swing.JMenuItem();
        MnuFurgoneta = new javax.swing.JMenuItem();
        MnuMoto = new javax.swing.JMenuItem();
        MnuCrearVehiculo = new javax.swing.JCheckBoxMenuItem();
        MnuInformes = new javax.swing.JMenu();
        MnuInformeVehiculos = new javax.swing.JMenuItem();
        MnuInformeAlquilados = new javax.swing.JMenuItem();
        MnuUsuarios = new javax.swing.JMenuItem();
        MnuCrearusuario = new javax.swing.JMenuItem();
        MnuCerrarSesion = new javax.swing.JMenuItem();
        MnuSalirr = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JflmLogin.setIconifiable(true);
        JflmLogin.setResizable(true);
        JflmLogin.setTitle("Login");
        JflmLogin.setVisible(true);

        jLabel1.setText("*Correo:");

        jLabel2.setText("*Contraseña:");

        jScrollPane1.setViewportView(TxtCorreo);

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JflmLoginLayout = new javax.swing.GroupLayout(JflmLogin.getContentPane());
        JflmLogin.getContentPane().setLayout(JflmLoginLayout);
        JflmLoginLayout.setHorizontalGroup(
            JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JflmLoginLayout.createSequentialGroup()
                .addGroup(JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JflmLoginLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(TxtContraseña)))
                    .addGroup(JflmLoginLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        JflmLoginLayout.setVerticalGroup(
            JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JflmLoginLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JflmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        desktopPane.add(JflmLogin);
        JflmLogin.setBounds(30, 30, 420, 280);

        JifUsuarios.setClosable(true);
        JifUsuarios.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifUsuarios.setIconifiable(true);
        JifUsuarios.setMaximizable(true);
        JifUsuarios.setResizable(true);
        JifUsuarios.setTitle("Listado De Usuarios");
        JifUsuarios.setVisible(false);

        TblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cedula", "Correo", "Password", "Tipo usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TblUsuarios);

        javax.swing.GroupLayout JifUsuariosLayout = new javax.swing.GroupLayout(JifUsuarios.getContentPane());
        JifUsuarios.getContentPane().setLayout(JifUsuariosLayout);
        JifUsuariosLayout.setHorizontalGroup(
            JifUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JifUsuariosLayout.setVerticalGroup(
            JifUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifUsuariosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        desktopPane.add(JifUsuarios);
        JifUsuarios.setBounds(170, 30, 519, 371);

        JifMoto.setClosable(true);
        JifMoto.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifMoto.setIconifiable(true);
        JifMoto.setMaximizable(true);
        JifMoto.setResizable(true);
        JifMoto.setTitle("Listado de Motos");
        JifMoto.setVisible(false);

        TblMoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Km", "Estado", "Valor alquiler", "Casco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TblMoto);

        BtnDevolverMoto.setText("Devolver");

        BtnAlquilarMoto.setText("Alquilar");
        BtnAlquilarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlquilarMotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JifMotoLayout = new javax.swing.GroupLayout(JifMoto.getContentPane());
        JifMoto.getContentPane().setLayout(JifMotoLayout);
        JifMotoLayout.setHorizontalGroup(
            JifMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifMotoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(JifMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAlquilarMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDevolverMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        JifMotoLayout.setVerticalGroup(
            JifMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifMotoLayout.createSequentialGroup()
                .addGroup(JifMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JifMotoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JifMotoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(BtnAlquilarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDevolverMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(314, Short.MAX_VALUE))
        );

        desktopPane.add(JifMoto);
        JifMoto.setBounds(210, 10, 770, 549);

        JifCoche.setClosable(true);
        JifCoche.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifCoche.setIconifiable(true);
        JifCoche.setMaximizable(true);
        JifCoche.setResizable(true);
        JifCoche.setTitle("Listado De Coches");
        JifCoche.setVisible(false);

        TblCoche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Km", "Estado", "Valor alquiler", "Extras"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TblCoche);

        BtnDevolverCoche.setText("Devolver");

        BtnAlquilarCoche.setText("Alquilar");
        BtnAlquilarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlquilarCocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JifCocheLayout = new javax.swing.GroupLayout(JifCoche.getContentPane());
        JifCoche.getContentPane().setLayout(JifCocheLayout);
        JifCocheLayout.setHorizontalGroup(
            JifCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifCocheLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(JifCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAlquilarCoche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDevolverCoche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        JifCocheLayout.setVerticalGroup(
            JifCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifCocheLayout.createSequentialGroup()
                .addGroup(JifCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JifCocheLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JifCocheLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(BtnAlquilarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDevolverCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        desktopPane.add(JifCoche);
        JifCoche.setBounds(460, 70, 510, 340);

        JifFurgoneta.setClosable(true);
        JifFurgoneta.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifFurgoneta.setIconifiable(true);
        JifFurgoneta.setMaximizable(true);
        JifFurgoneta.setResizable(true);
        JifFurgoneta.setTitle("Listado De Furgonetas");
        JifFurgoneta.setVisible(false);

        TblFurgoneta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Km", "Estado", "Valor alquiler", "Capacidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Short.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TblFurgoneta);

        BtnAlquilarFurgoneta.setText("Alquilar");
        BtnAlquilarFurgoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlquilarFurgonetaActionPerformed(evt);
            }
        });

        BtnDevolverFurgoneta.setText("Devolver");

        javax.swing.GroupLayout JifFurgonetaLayout = new javax.swing.GroupLayout(JifFurgoneta.getContentPane());
        JifFurgoneta.getContentPane().setLayout(JifFurgonetaLayout);
        JifFurgonetaLayout.setHorizontalGroup(
            JifFurgonetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifFurgonetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(JifFurgonetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAlquilarFurgoneta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDevolverFurgoneta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        JifFurgonetaLayout.setVerticalGroup(
            JifFurgonetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifFurgonetaLayout.createSequentialGroup()
                .addGroup(JifFurgonetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JifFurgonetaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(BtnAlquilarFurgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDevolverFurgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JifFurgonetaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        desktopPane.add(JifFurgoneta);
        JifFurgoneta.setBounds(350, 110, 490, 310);

        JifAlquilarVehiculos.setClosable(true);
        JifAlquilarVehiculos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifAlquilarVehiculos.setIconifiable(true);
        JifAlquilarVehiculos.setMaximizable(true);
        JifAlquilarVehiculos.setResizable(true);
        JifAlquilarVehiculos.setTitle("Alquilar Vehiculos");
        JifAlquilarVehiculos.setVisible(false);

        TblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Km", "Disponibilidad", "Valor Alquiler", "Tipo de Vehiculo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(TblVehiculos);

        jLabel8.setText("Matricula Del Vehiculo:");

        jLabel9.setText("Cedula del Cliente");

        jLabel10.setText("Fecha De Entrega:");

        jLabel11.setText("Fecha Devolucion:");

        BtnAlquilar.setText("Alquilar");
        BtnAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlquilarActionPerformed(evt);
            }
        });

        TblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cedula", "Identificacion", "Tipo de Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(TblCliente);

        javax.swing.GroupLayout JifAlquilarVehiculosLayout = new javax.swing.GroupLayout(JifAlquilarVehiculos.getContentPane());
        JifAlquilarVehiculos.getContentPane().setLayout(JifAlquilarVehiculosLayout);
        JifAlquilarVehiculosLayout.setHorizontalGroup(
            JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                .addGroup(JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtNombreClienteAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(TxtMatriculaAlquilar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jDateEntregaAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jDateDevolucionAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(BtnAlquilar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        JifAlquilarVehiculosLayout.setVerticalGroup(
            JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(TxtMatriculaAlquilar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(jDateEntregaAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(TxtNombreClienteAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jDateDevolucionAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(BtnAlquilar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(JifAlquilarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JifAlquilarVehiculosLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(327, Short.MAX_VALUE)))
        );

        desktopPane.add(JifAlquilarVehiculos);
        JifAlquilarVehiculos.setBounds(270, 90, 530, 330);

        JifCrearUsuario.setClosable(true);
        JifCrearUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifCrearUsuario.setIconifiable(true);
        JifCrearUsuario.setMaximizable(true);
        JifCrearUsuario.setResizable(true);
        JifCrearUsuario.setTitle("Crear Usuario");
        JifCrearUsuario.setVisible(false);

        jLabel3.setText("Nombre:");

        TxtNombreCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreCrearUsuarioActionPerformed(evt);
            }
        });

        TxtIdentifiacionCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdentifiacionCrearUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Identificacion:");

        TxtCorreoCrearUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCorreoCrearUsuActionPerformed(evt);
            }
        });

        jLabel5.setText("Correo:");

        TxtContraseñaCrearUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContraseñaCrearUsuActionPerformed(evt);
            }
        });

        jLabel6.setText("Contraseña:");

        BtnCrearUsu.setText("Crear Usuario");
        BtnCrearUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearUsuActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de usuario:");

        CbxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Alquiler", "Cliente", " " }));
        CbxTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTipoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JifCrearUsuarioLayout = new javax.swing.GroupLayout(JifCrearUsuario.getContentPane());
        JifCrearUsuario.getContentPane().setLayout(JifCrearUsuarioLayout);
        JifCrearUsuarioLayout.setHorizontalGroup(
            JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifCrearUsuarioLayout.createSequentialGroup()
                .addGroup(JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JifCrearUsuarioLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JifCrearUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TxtCorreoCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(JifCrearUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TxtIdentifiacionCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JifCrearUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TxtNombreCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(JifCrearUsuarioLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtContraseñaCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JifCrearUsuarioLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(BtnCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        JifCrearUsuarioLayout.setVerticalGroup(
            JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifCrearUsuarioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombreCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIdentifiacionCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCorreoCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtContraseñaCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(JifCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(BtnCrearUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        desktopPane.add(JifCrearUsuario);
        JifCrearUsuario.setBounds(470, 140, 437, 463);

        JifInformeAlquilados.setClosable(true);
        JifInformeAlquilados.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifInformeAlquilados.setIconifiable(true);
        JifInformeAlquilados.setMaximizable(true);
        JifInformeAlquilados.setResizable(true);
        JifInformeAlquilados.setTitle("Vehiculos Alquilados");
        JifInformeAlquilados.setVisible(false);

        TblVehiculosAlquilados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vehiculo", "Cliente", "Fecha de entrega", "Fecha de devolucion"
            }
        ));
        jScrollPane7.setViewportView(TblVehiculosAlquilados);

        javax.swing.GroupLayout JifInformeAlquiladosLayout = new javax.swing.GroupLayout(JifInformeAlquilados.getContentPane());
        JifInformeAlquilados.getContentPane().setLayout(JifInformeAlquiladosLayout);
        JifInformeAlquiladosLayout.setHorizontalGroup(
            JifInformeAlquiladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifInformeAlquiladosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JifInformeAlquiladosLayout.setVerticalGroup(
            JifInformeAlquiladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifInformeAlquiladosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        desktopPane.add(JifInformeAlquilados);
        JifInformeAlquilados.setBounds(330, 100, 470, 290);

        JifCrearVehiculo.setClosable(true);
        JifCrearVehiculo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifCrearVehiculo.setIconifiable(true);
        JifCrearVehiculo.setMaximizable(true);
        JifCrearVehiculo.setResizable(true);
        JifCrearVehiculo.setTitle("Crear Vehiculo");
        JifCrearVehiculo.setVisible(false);

        jLabel12.setText("Tipo De Vehiculo:");

        JcbCoche.setText("Coche");
        JcbCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbCocheActionPerformed(evt);
            }
        });

        JcbFurgoneta.setText("Furgoneta");

        JcbMoto.setText("Moto");

        jLabel13.setText("Matricula:");

        jLabel14.setText("KM:");

        jLabel15.setText("Valor Alquiler:");

        jLabel16.setText("Disponibilidad:");

        JcbDisponible.setText("Disponible");

        jLabel17.setText("Otros:");

        JcbCasco.setText("Casco");

        JcbExtras.setText("Extras");

        jLabel18.setText("Capacidad:");

        BtnCrearVehiculo.setText("Crear Vehiculo");
        BtnCrearVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JifCrearVehiculoLayout = new javax.swing.GroupLayout(JifCrearVehiculo.getContentPane());
        JifCrearVehiculo.getContentPane().setLayout(JifCrearVehiculoLayout);
        JifCrearVehiculoLayout.setHorizontalGroup(
            JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifCrearVehiculoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JifCrearVehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(JcbCoche)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JifCrearVehiculoLayout.createSequentialGroup()
                        .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcbCasco)
                            .addComponent(TxtMatriculaCrearVehiculo)
                            .addComponent(TxtValorCrearVehi))))
                .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JifCrearVehiculoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JcbDisponible))
                    .addGroup(JifCrearVehiculoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JifCrearVehiculoLayout.createSequentialGroup()
                                .addComponent(JcbExtras)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JspCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JifCrearVehiculoLayout.createSequentialGroup()
                                .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JcbFurgoneta)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JcbMoto)
                                    .addComponent(TxtKmCrearVehi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(JifCrearVehiculoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(BtnCrearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111))
        );
        JifCrearVehiculoLayout.setVerticalGroup(
            JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifCrearVehiculoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(JcbCoche)
                    .addComponent(JcbFurgoneta)
                    .addComponent(JcbMoto))
                .addGap(43, 43, 43)
                .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxtMatriculaCrearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(TxtKmCrearVehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(TxtValorCrearVehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JcbDisponible))
                .addGap(27, 27, 27)
                .addGroup(JifCrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(JcbCasco)
                    .addComponent(JcbExtras)
                    .addComponent(jLabel18)
                    .addComponent(JspCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCrearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        desktopPane.add(JifCrearVehiculo);
        JifCrearVehiculo.setBounds(470, 70, 350, 270);

        JifInformeVehiculos.setClosable(true);
        JifInformeVehiculos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        JifInformeVehiculos.setIconifiable(true);
        JifInformeVehiculos.setMaximizable(true);
        JifInformeVehiculos.setResizable(true);
        JifInformeVehiculos.setTitle("Informe Vehiculos");
        JifInformeVehiculos.setVisible(false);

        TblInformeVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Km", "Disponibilidad", "Valor alquiler", "Tipo de vehiculo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane10.setViewportView(TblInformeVehiculos);

        javax.swing.GroupLayout JifInformeVehiculosLayout = new javax.swing.GroupLayout(JifInformeVehiculos.getContentPane());
        JifInformeVehiculos.getContentPane().setLayout(JifInformeVehiculosLayout);
        JifInformeVehiculosLayout.setHorizontalGroup(
            JifInformeVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifInformeVehiculosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JifInformeVehiculosLayout.setVerticalGroup(
            JifInformeVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JifInformeVehiculosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        desktopPane.add(JifInformeVehiculos);
        JifInformeVehiculos.setBounds(510, 140, 300, 230);

        MmuLogin.setMnemonic('f');
        MmuLogin.setText("Menu");
        MmuLogin.setEnabled(false);

        MnuVehiculos.setText("Vehiculos");

        MnuCoche.setText("Coche");
        MnuCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCocheActionPerformed(evt);
            }
        });
        MnuVehiculos.add(MnuCoche);

        MnuFurgoneta.setText("Furgoneta");
        MnuFurgoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuFurgonetaActionPerformed(evt);
            }
        });
        MnuVehiculos.add(MnuFurgoneta);

        MnuMoto.setText("Moto");
        MnuMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuMotoActionPerformed(evt);
            }
        });
        MnuVehiculos.add(MnuMoto);

        MnuCrearVehiculo.setSelected(true);
        MnuCrearVehiculo.setText("Crear Vehiculo");
        MnuCrearVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCrearVehiculoActionPerformed(evt);
            }
        });
        MnuVehiculos.add(MnuCrearVehiculo);

        MmuLogin.add(MnuVehiculos);

        MnuInformes.setText("Informes");

        MnuInformeVehiculos.setText("Informe vehiculos");
        MnuInformeVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuInformeVehiculosActionPerformed(evt);
            }
        });
        MnuInformes.add(MnuInformeVehiculos);

        MnuInformeAlquilados.setText("Alquilados");
        MnuInformeAlquilados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuInformeAlquiladosActionPerformed(evt);
            }
        });
        MnuInformes.add(MnuInformeAlquilados);

        MmuLogin.add(MnuInformes);

        MnuUsuarios.setMnemonic('s');
        MnuUsuarios.setText("Usuarios");
        MnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuUsuariosActionPerformed(evt);
            }
        });
        MmuLogin.add(MnuUsuarios);

        MnuCrearusuario.setText("Crear usuario");
        MnuCrearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCrearusuarioActionPerformed(evt);
            }
        });
        MmuLogin.add(MnuCrearusuario);

        MnuCerrarSesion.setMnemonic('x');
        MnuCerrarSesion.setText("Cerrar sesion");
        MnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCerrarSesionActionPerformed(evt);
            }
        });
        MmuLogin.add(MnuCerrarSesion);

        MnuSalirr.setText("Salir");
        MnuSalirr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSalirrActionPerformed(evt);
            }
        });
        MmuLogin.add(MnuSalirr);

        menuBar.add(MmuLogin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCerrarSesionActionPerformed
        MmuLogin.setEnabled(false);
        TxtCorreo.setText("");
        TxtContraseña.setText("");
        usuarioAutenticado = null;
        iniciarMenus(false);
        JflmLogin.show();


    }//GEN-LAST:event_MnuCerrarSesionActionPerformed

    private void pintarUsuarios() {
        DefaultTableModel model = (DefaultTableModel) TblUsuarios.getModel();
        model.getDataVector().removeAllElements();
        for (Usuario usuario : gestionUsuario1.getUsuarios()) {
            model.addRow(usuario.obtenerArregloObjeto());
        }
        TblUsuarios.setModel(model);

    }

    private void pintarCliente() {
        DefaultTableModel model = (DefaultTableModel) TblCliente.getModel();
        model.getDataVector().removeAllElements();
        for (Cliente cliente : gestionUsuario1.getClientes()) {
            model.addRow(cliente.obtenerArregloObjeto());
        }
        TblCliente.setModel(model);

    }

    private void pintarVehiculosAlquilados() {
        DefaultTableModel model = (DefaultTableModel) TblVehiculosAlquilados.getModel();
        model.getDataVector().removeAllElements();
        for (AlquilaVehiculo vehiculo : gestionVehiculo.getVehiculosAlquilados()) {
            model.addRow(vehiculo.obtenerArregloVehiculoAlquilado());

        }
        TblVehiculosAlquilados.setModel(model);

    }

    private void MnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuUsuariosActionPerformed
        // TODO add your handling code here:
        gestionUsuario.llenarUsuarios();
        pintarUsuarios();

//        llenarTablaUsuario();
//        llenarTablaCliente();
        JifUsuarios.repaint();
        JifUsuarios.show();
        if (JifUsuarios.isIcon()) {
            try {
                JifUsuarios.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_MnuUsuariosActionPerformed
private void llenarTablaInforme()
    {
        DefaultTableModel model = (DefaultTableModel) TblInformeVehiculos.getModel();
        model.getDataVector().removeAllElements();
        for (AbstractVehiculo vehiculo : gestionVehiculo.obtenerVehiculos("Vehiculos"))
        {
            model.addRow(vehiculo.obtenerArregloObjeto());
        }
        TblInformeVehiculos.setModel(model);

    }
    
    
    private void llenarTablaVhs()
 
    {
        DefaultTableModel model = (DefaultTableModel) TblVehiculos.getModel();
        model.getDataVector().removeAllElements();
        for (AbstractVehiculo vehiculo : gestionVehiculo.obtenerVehiculos("Vehiculos"))
        {
            if (vehiculo.isEstado() == true)
            {
                model.addRow(vehiculo.obtenerArregloObjeto());
            }
        }
        TblVehiculos.setModel(model);

    }

    private void pintarCoches() {
        DefaultTableModel model = (DefaultTableModel) TblCoche.getModel();
        model.getDataVector().removeAllElements();

        for (AbstractVehiculo coche : gestionVehiculo.obtenerVehiculos("Coche")) {
            model.addRow(coche.obtenerArregloObjeto());
        }
        TblCoche.setModel(model);

    }


    private void MnuCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCocheActionPerformed
        // TODO add your handling code here:

        gestionVehiculo.llenarVehiculos();
        pintarCoches();
        JifCoche.repaint();
        JifCoche.show();

        if (JifCoche.isIcon()) {
            try {
                JifCoche.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_MnuCocheActionPerformed

    private void pintarFurgonetas() {
        DefaultTableModel model = (DefaultTableModel) TblFurgoneta.getModel();
        model.getDataVector().removeAllElements();

        for (AbstractVehiculo furgoneta : gestionVehiculo.obtenerVehiculos("Furgoneta")) {
            model.addRow(furgoneta.obtenerArregloObjeto());
        }
        TblFurgoneta.setModel(model);

    }


    private void MnuFurgonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuFurgonetaActionPerformed
        // TODO add your handling code here:
        gestionVehiculo.llenarVehiculos();
        pintarFurgonetas();
        JifFurgoneta.repaint();
        JifFurgoneta.show();

        if (JifFurgoneta.isIcon()) {
            try {
                JifFurgoneta.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_MnuFurgonetaActionPerformed

    private void pintarMotos() {
        DefaultTableModel model = (DefaultTableModel) TblMoto.getModel();
        model.getDataVector().removeAllElements();

        for (AbstractVehiculo moto : gestionVehiculo.obtenerVehiculos("Moto")) {
            model.addRow(moto.obtenerArregloObjeto());
        }
        TblMoto.setModel(model);

    }

    private void MnuMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuMotoActionPerformed
        // TODO add your handling code here:

        gestionVehiculo.llenarVehiculos();

        pintarMotos();
        JifMoto.repaint();
        JifMoto.show();

        if (JifMoto.isIcon()) {
            try {
                JifMoto.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_MnuMotoActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        // TODO add your handling code here:
        if (TxtCorreo.getText() == null || TxtCorreo.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe diligenciar el correo", "Datos Faltantes", 2);
        } else if (TxtContraseña.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe diligenciar la contraseña", "Datos Faltantes", 2);
        } else {
            gestionUsuario = new GestionUsuario();

            //Significa que diligencio correo y contraseña
            Pattern pattern = Pattern.compile("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");
            Matcher matcher = pattern.matcher(TxtCorreo.getText());

            if (matcher.find() == true) {
                usuarioAutenticado = gestionUsuario.
                        encontrarUsuario(TxtCorreo.getText(), TxtContraseña.getText());
                if (usuarioAutenticado == null) {
                    JOptionPane.showMessageDialog(this,
                            "El usuario Ingresado no existe", "Datos Erróneos", 0);
                } else {
                    gestionUsuario = new GestionUsuario();

                    JOptionPane.showMessageDialog(this,
                            "Bienvenido " + usuarioAutenticado, "Bienvenido", 1);
                    MmuLogin.setEnabled(true);
                    gestionarPermisosMenu();
                    JflmLogin.hide();
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "El correo no tiene un formato válido", "Datos Erróneos", 0);

            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiVehiculos().setVisible(true);
            }
        });
    }

    {
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void MnuSalirrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSalirrActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MnuSalirrActionPerformed

    private void TxtNombreCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreCrearUsuarioActionPerformed

    private void TxtIdentifiacionCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdentifiacionCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdentifiacionCrearUsuarioActionPerformed

    private void TxtCorreoCrearUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCorreoCrearUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCorreoCrearUsuActionPerformed

    private void TxtContraseñaCrearUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContraseñaCrearUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContraseñaCrearUsuActionPerformed

    private void BtnCrearUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearUsuActionPerformed
        // TODO add your handling code here:

        gestionUsuario1.getTipoUsuarios();
        TipoUsuario[] tipos;

        if (CbxTipoUsuario.getSelectedItem().toString().equals("Administrador") || CbxTipoUsuario.getSelectedItem().toString().equals("Alquiler")) {
            if (TxtNombreCrearUsuario.getText() == null || TxtNombreCrearUsuario.getText().compareTo("") == 0) {
                JOptionPane.showMessageDialog(this, "Debe escribir su nombre", "Datos Faltantes", 2);
            } else if (TxtIdentifiacionCrearUsuario.getText() == null || TxtIdentifiacionCrearUsuario.getText().compareTo("") == 0) {
                JOptionPane.showMessageDialog(this, "Debe escribir su identificacion", "Datos Faltantes", 2);
            } else if (TxtCorreo.getText() == null || TxtCorreo.getText().compareTo("") == 0) {
                JOptionPane.showMessageDialog(this, "Debe escribir un correo electronico", "Datos Faltantes", 2);
            } else if (TxtContraseñaCrearUsu.getText() == null || TxtContraseñaCrearUsu.getText().compareTo("") == 0) {
                JOptionPane.showMessageDialog(this, "Debe escribir una contraseña", "Datos Faltantes", 2);
            } else {

                String codigo = CbxTipoUsuario.getSelectedItem().toString().toLowerCase();
                byte numTipo = leer.convertirTipoUsuarios(codigo);
                tipos = gestionUsuario1.getTipoUsuarios();
                Usuario usuario = new Usuario(TxtNombreCrearUsuario.getText(), TxtIdentifiacionCrearUsuario.getText(), TxtCorreo.getText(), TxtContraseñaCrearUsu.getText(), tipos[numTipo]);

                try {
                    gestionUsuario1.adicionarUsuario(usuario);
                    pintarUsuarios();
                    pintarCliente();
                    TxtNombreCrearUsuario.setText("");
                    TxtIdentifiacionCrearUsuario.setText("");
                    TxtCorreo.setText("");
                    TxtContraseñaCrearUsu.setText("");
                } catch (ClienteExcepcion ex) {
                    JOptionPane.showMessageDialog(this,
                            ex.getMessage(), "error en el usuario", 0);
                }
            }
        } else {
            if (TxtNombreCrearUsuario.getText() == null || TxtNombreCrearUsuario.getText().compareTo("") == 0) {
                JOptionPane.showMessageDialog(this, "Debe escribir su nombre", "Datos Faltantes", 2);
            } else if (TxtIdentifiacionCrearUsuario.getText() == null || TxtIdentifiacionCrearUsuario.getText().compareTo("") == 0) {
                JOptionPane.showMessageDialog(this, "Debe escribir su identificacion", "Datos Faltantes", 2);
            }

            //Crear cliente 
            Cliente cliente = new Cliente(TxtNombreCrearUsuario.getText(), TxtIdentifiacionCrearUsuario.getText());
            try {
                gestionUsuario1.adicionarCliente(cliente);
                pintarUsuarios();
                pintarCliente();
                TxtNombreCrearUsuario.setText("");
                TxtIdentifiacionCrearUsuario.setText("");
                TxtCorreo.setText("");
                TxtContraseñaCrearUsu.setText("");
            } catch (VehiculoExcepcion ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(), "error en el cliente", 0);
            }

        }


    }//GEN-LAST:event_BtnCrearUsuActionPerformed

    private void CbxTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTipoUsuarioActionPerformed
        // TODO add your handling code here:

        if (CbxTipoUsuario.getSelectedItem().toString().equals("Client")) {
            TxtCorreo.setEnabled(false);
            TxtContraseñaCrearUsu.setEnabled(false);
        } else {
            TxtContraseñaCrearUsu.setEnabled(true);
            TxtCorreo.setEnabled(true);
        }
    }//GEN-LAST:event_CbxTipoUsuarioActionPerformed

    private void MnuCrearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCrearusuarioActionPerformed
        // TODO add your handling code here:
        JifCrearUsuario.repaint();
        JifCrearUsuario.show();
        if (JifCrearUsuario.isIcon()) {
            try {
                JifCrearUsuario.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_MnuCrearusuarioActionPerformed

    private void BtnAlquilarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlquilarMotoActionPerformed
        // TODO add your handling code here:
        Date fecha = new Date();
        jDateEntregaAlquiler.setDate(fecha);
        pintarCliente();
        llenarTablaVhs();
        
       
        JifAlquilarVehiculos.show();
        if (JifAlquilarVehiculos.isIcon()) {
            try {
                JifAlquilarVehiculos.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnAlquilarMotoActionPerformed

    private void BtnAlquilarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlquilarCocheActionPerformed
        // TODO add your handling code here:
        Date fecha = new Date();
        jDateEntregaAlquiler.setDate(fecha);
      pintarCliente();
        llenarTablaVhs();
      
        JifAlquilarVehiculos.show();
        if (JifAlquilarVehiculos.isIcon()) {
            try {
                JifAlquilarVehiculos.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnAlquilarCocheActionPerformed

    private void BtnAlquilarFurgonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlquilarFurgonetaActionPerformed
        // TODO add your handling code here:
        Date fecha = new Date();
        jDateEntregaAlquiler.setDate(fecha);
        pintarCliente();
        llenarTablaVhs();
        
       
        JifAlquilarVehiculos.show();
        if (JifAlquilarVehiculos.isIcon()) {
            try {
                JifAlquilarVehiculos.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnAlquilarFurgonetaActionPerformed
    public Date sumarRestarDiasFecha(Date fecha) {
        Date a;
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fecha); // Configuramos la fecha que se recibe

        calendar.add(Calendar.DAY_OF_YEAR, -1);  // numero de días a añadir, o restar en caso de días<0

        return a = calendar.getTime(); // Devuelve el objeto Date con los nuevos días añadidos

    }
    private void BtnAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlquilarActionPerformed
        // TODO add your handling code here:

        Date hoy = new Date();
        Date fecha = sumarRestarDiasFecha(hoy);
        
//        gestionVehiculo.llenarVehiculos();

//        for (AbstractVehiculo vehi : gestionVehiculo.obtenerVehiculos("Coche")) {

//            if (TxtMatriculaAlquilar.getText() == vehi.getMatricula()) {

                if (TxtNombreClienteAlquiler.getText() == null || TxtNombreClienteAlquiler.getText().compareTo("") == 0)
                {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente");
                } 
                else if (TxtMatriculaAlquilar.getText() == null || TxtMatriculaAlquilar.getText().compareTo("") == 0) 
                {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un vehículo");
                }
                else if (jDateEntregaAlquiler.getDate() == null) 
                {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de entrega");
                } 
                else if (jDateEntregaAlquiler.getDate().before(fecha)) 
                {
                    JOptionPane.showMessageDialog(this, "La fecha de alquiler es anterior a la fecha actual");
                } 
                else if (jDateDevolucionAlquiler.getDate() == null) 
                {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de devolución");
                } 
                else if (jDateEntregaAlquiler.getDate().compareTo(jDateDevolucionAlquiler.getDate()) > 0) 
                {
                    JOptionPane.showMessageDialog(this, "La fecha de devolucion es anterior a la fecha de alquiler");
                } else {

                    if (gestionVehiculo.encontrarVehiculo(TxtMatriculaAlquilar.getText()).isEstado() == false) {

                        JOptionPane.showMessageDialog(this, "El vehículo de matricula " + TxtMatriculaAlquilar.getText()
                                + " se encuentra ocupado");
                        TxtMatriculaAlquilar.setText("");
                    } else {

                        AlquilaVehiculo alquilado = new AlquilaVehiculo(gestionVehiculo.encontrarVehiculo(TxtMatriculaAlquilar.getText()),
                                jDateEntregaAlquiler.getDate(), jDateDevolucionAlquiler.getDate(),
                                gestionUsuario1.encontrarCliente(TxtNombreClienteAlquiler.getText()));

                        try {

                            gestionVehiculo.encontrarVehiculo(TxtMatriculaAlquilar.getText()).alquilar();
                            gestionVehiculo.adicionarVehiculoAlquilado(alquilado);
                            llenarTablaVhs();
                            pintarVehiculosAlquilados();
                           llenarTablaInforme();
                            JOptionPane.showMessageDialog(this, "El vehiculo " + TxtMatriculaAlquilar.getText()
                                    + " fue alquilado a " + TxtNombreClienteAlquiler.getText());
                            TxtMatriculaAlquilar.setText("");
                            TxtNombreClienteAlquiler.setText("");

                        } catch (VehiculoExcepcion ex) {
                            Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }

//            } else {
//
//                JOptionPane.showMessageDialog(null, "Vehiculo no esta  registrado ");
//            }
//
//        }


    }//GEN-LAST:event_BtnAlquilarActionPerformed

    private void MnuInformeAlquiladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuInformeAlquiladosActionPerformed
        // TODO add your handling code here:
        pintarVehiculosAlquilados();
        JifInformeAlquilados
                .repaint();
        JifInformeAlquilados
                .show();

        if (JifInformeAlquilados
                .isIcon()) {
            try {

                JifInformeAlquilados
                        .setMaximum(true);

            } catch (PropertyVetoException ex) {
                Logger
                        .getLogger(MdiVehiculos.class
                                .getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_MnuInformeAlquiladosActionPerformed

    private void MnuInformeVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuInformeVehiculosActionPerformed
        // TODO add your handling code here:
       gestionVehiculo.llenarVehiculos();
        llenarTablaInforme();
        JifInformeVehiculos.repaint();
        JifInformeVehiculos.show();

        if (JifInformeVehiculos.isIcon())
        {
            try
            {
                JifInformeVehiculos.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MdiVehiculos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_MnuInformeVehiculosActionPerformed

    private void BtnCrearVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearVehiculoActionPerformed
        // TODO add your handling code here:
        if (TxtMatriculaCrearVehiculo
                .getText() == null || TxtMatriculaCrearVehiculo
                        .getText().compareTo("") == 0) {
            JOptionPane
                    .showMessageDialog(this, "Debe escribir la matricula del vehículo");

        } else if (TxtKmCrearVehi
                .getText() == null || TxtKmCrearVehi
                        .getText().compareTo("") == 0) {
            JOptionPane
                    .showMessageDialog(this, "Debe escribir el kilometraje del vehículo");

        } else if (TxtValorCrearVehi
                .getText() == null || TxtValorCrearVehi
                        .getText().compareTo("") == 0) {
            JOptionPane
                    .showMessageDialog(this, "Ingrese el valor del alquiler");

        } else if (!JcbCoche
                .isSelected() && !JcbFurgoneta
                        .isSelected() && !JcbMoto
                        .isSelected()) {
            JOptionPane
                    .showMessageDialog(this, "Debe seleccionar el tipo de vehículo");

        } else {
            if (JcbMoto
                    .isSelected() == true) {
                Moto moto
                        = new Moto(TxtMatriculaCrearVehiculo
                                .getText(), Integer
                                        .parseInt(TxtKmCrearVehi
                                                .getText()), JcbDisponible
                                        .isSelected(), Double
                                        .parseDouble(TxtValorCrearVehi
                                                .getText()));

                try {
                    gestionVehiculo
                            .adicionarVehiculo(moto
                            );
                    pintarMotos();
                    JOptionPane
                            .showMessageDialog(this, "Vehículo creado");

                } catch (VehiculoExcepcion ex) {
                    JOptionPane
                            .showMessageDialog(this, ex
                                    .getMessage(), "Error al crear el vehiculo", 0);

                }
                TxtKmCrearVehi
                        .setText("");
                TxtMatriculaCrearVehiculo
                        .setText("");
                TxtValorCrearVehi
                        .setText("");
                JcbDisponible
                        .setSelected(false);
                JcbMoto
                        .setSelected(false);
                JcbCasco
                        .setSelected(false);

            } else if (JcbCoche
                    .isSelected() == true) {
                Coche coche
                        = new Coche(TxtMatriculaCrearVehiculo
                                .getText(), Integer
                                        .parseInt(TxtKmCrearVehi
                                                .getText()), JcbDisponible
                                        .isSelected(), Double
                                        .parseDouble(TxtValorCrearVehi
                                                .getText()));

                try {
                    gestionVehiculo
                            .adicionarVehiculo(coche
                            );
                    pintarCoches();
                    JOptionPane
                            .showMessageDialog(this, "Vehículo creado");

                } catch (VehiculoExcepcion ex) {
                    JOptionPane
                            .showMessageDialog(this, ex
                                    .getMessage(), "Error al crear el vehiculo", 0);

                }
                TxtKmCrearVehi
                        .setText("");
                TxtMatriculaCrearVehiculo
                        .setText("");
                TxtValorCrearVehi
                        .setText("");
                JcbDisponible
                        .setSelected(false);
                JcbCoche
                        .setSelected(false);
                JcbExtras
                        .setSelected(false);

            } else if (JcbFurgoneta
                    .isSelected() == true) {
                Furgoneta furgoneta
                        = new Furgoneta(TxtMatriculaCrearVehiculo
                                .getText(), Integer
                                        .parseInt(TxtKmCrearVehi
                                                .getText()), JcbDisponible
                                        .isSelected(), Double
                                        .parseDouble(TxtValorCrearVehi
                                                .getText()));

                try {

                    gestionVehiculo
                            .adicionarVehiculo(furgoneta
                            );
                    pintarFurgonetas();
                    JOptionPane
                            .showMessageDialog(this, "Vehículo creado");

                } catch (VehiculoExcepcion ex) {
                    JOptionPane
                            .showMessageDialog(this, ex
                                    .getMessage(), "Error al crear el vehiculo", 0);

                }
                TxtKmCrearVehi
                        .setText("");
                TxtMatriculaCrearVehiculo
                        .setText("");
                TxtValorCrearVehi
                        .setText("");
                JcbDisponible
                        .setSelected(false);
                JcbFurgoneta
                        .setSelected(false);
                JspCapacidad
                        .setValue(0);

            }

        }


    }//GEN-LAST:event_BtnCrearVehiculoActionPerformed

    private void JcbCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbCocheActionPerformed

    private void MnuCrearVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCrearVehiculoActionPerformed
        // TODO add your handling code here:

        JifCrearVehiculo
                .repaint();
        JifCrearVehiculo
                .show();
        JcbCasco
                .setEnabled(false);
        JcbExtras
                .setEnabled(false);
        JspCapacidad
                .setEnabled(false);
        validarCreacionVehi();

        if (JifCrearVehiculo
                .isIcon()) {
            try {
                JifCrearVehiculo
                        .setMaximum(true);

            } catch (PropertyVetoException ex) {
                Logger
                        .getLogger(MdiVehiculos.class
                                .getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_MnuCrearVehiculoActionPerformed

////
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlquilar;
    private javax.swing.JButton BtnAlquilarCoche;
    private javax.swing.JButton BtnAlquilarFurgoneta;
    private javax.swing.JButton BtnAlquilarMoto;
    private javax.swing.JButton BtnCrearUsu;
    private javax.swing.JButton BtnCrearVehiculo;
    private javax.swing.JButton BtnDevolverCoche;
    private javax.swing.JButton BtnDevolverFurgoneta;
    private javax.swing.JButton BtnDevolverMoto;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JComboBox<String> CbxTipoUsuario;
    private javax.swing.JCheckBox JcbCasco;
    private javax.swing.JCheckBox JcbCoche;
    private javax.swing.JCheckBox JcbDisponible;
    private javax.swing.JCheckBox JcbExtras;
    private javax.swing.JCheckBox JcbFurgoneta;
    private javax.swing.JCheckBox JcbMoto;
    private javax.swing.JInternalFrame JflmLogin;
    private javax.swing.JInternalFrame JifAlquilarVehiculos;
    private javax.swing.JInternalFrame JifCoche;
    private javax.swing.JInternalFrame JifCrearUsuario;
    private javax.swing.JInternalFrame JifCrearVehiculo;
    private javax.swing.JInternalFrame JifFurgoneta;
    private javax.swing.JInternalFrame JifInformeAlquilados;
    private javax.swing.JInternalFrame JifInformeVehiculos;
    private javax.swing.JInternalFrame JifMoto;
    private javax.swing.JInternalFrame JifUsuarios;
    private javax.swing.JSpinner JspCapacidad;
    private javax.swing.JMenu MmuLogin;
    private javax.swing.JMenuItem MnuCerrarSesion;
    private javax.swing.JMenuItem MnuCoche;
    private javax.swing.JCheckBoxMenuItem MnuCrearVehiculo;
    private javax.swing.JMenuItem MnuCrearusuario;
    private javax.swing.JMenuItem MnuFurgoneta;
    private javax.swing.JMenuItem MnuInformeAlquilados;
    private javax.swing.JMenuItem MnuInformeVehiculos;
    private javax.swing.JMenu MnuInformes;
    private javax.swing.JMenuItem MnuMoto;
    private javax.swing.JMenuItem MnuSalirr;
    private javax.swing.JMenuItem MnuUsuarios;
    private javax.swing.JMenu MnuVehiculos;
    private javax.swing.JTable TblCliente;
    private javax.swing.JTable TblCoche;
    private javax.swing.JTable TblFurgoneta;
    private javax.swing.JTable TblInformeVehiculos;
    private javax.swing.JTable TblMoto;
    private javax.swing.JTable TblUsuarios;
    private javax.swing.JTable TblVehiculos;
    private javax.swing.JTable TblVehiculosAlquilados;
    private javax.swing.JPasswordField TxtContraseña;
    private javax.swing.JTextField TxtContraseñaCrearUsu;
    private javax.swing.JTextPane TxtCorreo;
    private javax.swing.JTextField TxtCorreoCrearUsu;
    private javax.swing.JTextField TxtIdentifiacionCrearUsuario;
    private javax.swing.JTextField TxtKmCrearVehi;
    private javax.swing.JTextField TxtMatriculaAlquilar;
    private javax.swing.JTextField TxtMatriculaCrearVehiculo;
    private javax.swing.JTextField TxtNombreClienteAlquiler;
    private javax.swing.JTextField TxtNombreCrearUsuario;
    private javax.swing.JTextField TxtValorCrearVehi;
    private javax.swing.JDesktopPane desktopPane;
    private com.toedter.calendar.JDateChooser jDateDevolucionAlquiler;
    private com.toedter.calendar.JDateChooser jDateEntregaAlquiler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
